// Daftar pilihan "Wilayah cabang/site". Ubah sesuai daftar cabang resmi.
export const BRANCH_OPTIONS = [
  'Jakarta - Kantor Pusat',
  'Medan - Kantor Cabang',
  'Pekanbaru - Kantor Cabang',
  'Sorong - Kantor Cabang',
  'Banjarmasin - Kantor Cabang',
  'Lampung - Kantor Cabang',
  'Balikpapan - Kantor Cabang',
  'Jambi - Kantor Cabang',
  'Jayapura - Kantor Cabang',
  'Manado - Kantor Cabang',
  'Padang - Kantor Cabang',
  'Palembang - Kantor Cabang',
  'Palu - Kantor Cabang',
  'Pontianak - Kantor Cabang',
  'Surabaya - Kantor Cabang',
  'Samarinda - Kantor Cabang',
  'Semarang - Kantor Cabang',
  'Sampit - Kantor Cabang',
  'Tarakan - Kantor Cabang',
  'Ujung Pandang - Kantor Cabang',
  'Tanjung - Site',
  'Batu Kajang - Site',
  'Bendili - Site',
  'Bengalon - Site',
  'Bontang - Site',
  'Buhut - Site',
  'Tuhup - Site',
  'Muara Teweh - Site',
  'Damai - Site',
  'Muara Lawa - Site',
  'Tabang - Site',
  'Bharinto - Site',
  'Muara Tae - Site',
  'Timika - Site',
  'Loa Janan - Site',
  'Rantau - Site',
  'Sanggata - Site',
  'Satui & Senakin - Site',
  'Sorowako - Site',
  'Tanjung Enim - Site',
  'Tanjung Redeb - Site',
  'Tenggarong - Site',
  'Ambon - Kantor Perwakilan',
  'Manokwari - Kantor Perwakilan',
  'Bandung - Kantor Perwakilan',
  'Banda Aceh - Kantor Perwakilan',
  'Ternate - Kantor Perwakilan',
  'Kerinci - Kantor Perwakilan',
  'Bengkulu - Kantor Perwakilan',
  'Pangkal Pinang - Kantor Perwakilan',
  'Pangkalan Bun - Kantor Perwakilan',
  'Kendari - Kantor Perwakilan',
  'Merauke - Kantor Perwakilan',

] as const;